config/routes.rb
Rails.application.routes.draw do

  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # # end

  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id/edit', to: 'restaurants#edit'
  # patch 'restaurants/:id', to: 'restaurants#update'


  # delete "/restaurants/:id", to: "restaurants#destroy"

  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all  # Array of Restaurant
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurant
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'type your name...' %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edition du resto <%= @restaurant.name %></h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant %>
    </li>
  <% end %>
</ul>

<%= link_to 'Creer un restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Création d'un resto</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>

<%= link_to "Editer un restaurant", edit_restaurant_path(@restaurant) %>
|
<%= link_to 'Supprimer', restaurant_path(@restaurant),
            method: :delete, data: { confirm: 'Are you sure?' } %>